# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Pi3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Pi3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Pi3/CMakeFiles /home/pi/Pi3/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Pi3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Bike

# Build rule for target.
Bike: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bike
.PHONY : Bike

# fast build rule for target.
Bike/fast:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/build
.PHONY : Bike/fast

src/AD_HOC.o: src/AD_HOC.c.o

.PHONY : src/AD_HOC.o

# target to build an object file
src/AD_HOC.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/AD_HOC.c.o
.PHONY : src/AD_HOC.c.o

src/AD_HOC.i: src/AD_HOC.c.i

.PHONY : src/AD_HOC.i

# target to preprocess a source file
src/AD_HOC.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/AD_HOC.c.i
.PHONY : src/AD_HOC.c.i

src/AD_HOC.s: src/AD_HOC.c.s

.PHONY : src/AD_HOC.s

# target to generate assembly for a file
src/AD_HOC.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/AD_HOC.c.s
.PHONY : src/AD_HOC.c.s

src/Bluetooth_Phone.o: src/Bluetooth_Phone.c.o

.PHONY : src/Bluetooth_Phone.o

# target to build an object file
src/Bluetooth_Phone.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Bluetooth_Phone.c.o
.PHONY : src/Bluetooth_Phone.c.o

src/Bluetooth_Phone.i: src/Bluetooth_Phone.c.i

.PHONY : src/Bluetooth_Phone.i

# target to preprocess a source file
src/Bluetooth_Phone.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Bluetooth_Phone.c.i
.PHONY : src/Bluetooth_Phone.c.i

src/Bluetooth_Phone.s: src/Bluetooth_Phone.c.s

.PHONY : src/Bluetooth_Phone.s

# target to generate assembly for a file
src/Bluetooth_Phone.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Bluetooth_Phone.c.s
.PHONY : src/Bluetooth_Phone.c.s

src/Bluetooth_Pi0W.o: src/Bluetooth_Pi0W.c.o

.PHONY : src/Bluetooth_Pi0W.o

# target to build an object file
src/Bluetooth_Pi0W.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Bluetooth_Pi0W.c.o
.PHONY : src/Bluetooth_Pi0W.c.o

src/Bluetooth_Pi0W.i: src/Bluetooth_Pi0W.c.i

.PHONY : src/Bluetooth_Pi0W.i

# target to preprocess a source file
src/Bluetooth_Pi0W.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Bluetooth_Pi0W.c.i
.PHONY : src/Bluetooth_Pi0W.c.i

src/Bluetooth_Pi0W.s: src/Bluetooth_Pi0W.c.s

.PHONY : src/Bluetooth_Pi0W.s

# target to generate assembly for a file
src/Bluetooth_Pi0W.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Bluetooth_Pi0W.c.s
.PHONY : src/Bluetooth_Pi0W.c.s

src/Button_ISR.o: src/Button_ISR.c.o

.PHONY : src/Button_ISR.o

# target to build an object file
src/Button_ISR.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Button_ISR.c.o
.PHONY : src/Button_ISR.c.o

src/Button_ISR.i: src/Button_ISR.c.i

.PHONY : src/Button_ISR.i

# target to preprocess a source file
src/Button_ISR.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Button_ISR.c.i
.PHONY : src/Button_ISR.c.i

src/Button_ISR.s: src/Button_ISR.c.s

.PHONY : src/Button_ISR.s

# target to generate assembly for a file
src/Button_ISR.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/Button_ISR.c.s
.PHONY : src/Button_ISR.c.s

src/OBDII.o: src/OBDII.c.o

.PHONY : src/OBDII.o

# target to build an object file
src/OBDII.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/OBDII.c.o
.PHONY : src/OBDII.c.o

src/OBDII.i: src/OBDII.c.i

.PHONY : src/OBDII.i

# target to preprocess a source file
src/OBDII.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/OBDII.c.i
.PHONY : src/OBDII.c.i

src/OBDII.s: src/OBDII.c.s

.PHONY : src/OBDII.s

# target to generate assembly for a file
src/OBDII.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/OBDII.c.s
.PHONY : src/OBDII.c.s

src/SerialDriver.o: src/SerialDriver.c.o

.PHONY : src/SerialDriver.o

# target to build an object file
src/SerialDriver.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/SerialDriver.c.o
.PHONY : src/SerialDriver.c.o

src/SerialDriver.i: src/SerialDriver.c.i

.PHONY : src/SerialDriver.i

# target to preprocess a source file
src/SerialDriver.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/SerialDriver.c.i
.PHONY : src/SerialDriver.c.i

src/SerialDriver.s: src/SerialDriver.c.s

.PHONY : src/SerialDriver.s

# target to generate assembly for a file
src/SerialDriver.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/SerialDriver.c.s
.PHONY : src/SerialDriver.c.s

src/VoiceCommands.o: src/VoiceCommands.c.o

.PHONY : src/VoiceCommands.o

# target to build an object file
src/VoiceCommands.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/VoiceCommands.c.o
.PHONY : src/VoiceCommands.c.o

src/VoiceCommands.i: src/VoiceCommands.c.i

.PHONY : src/VoiceCommands.i

# target to preprocess a source file
src/VoiceCommands.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/VoiceCommands.c.i
.PHONY : src/VoiceCommands.c.i

src/VoiceCommands.s: src/VoiceCommands.c.s

.PHONY : src/VoiceCommands.s

# target to generate assembly for a file
src/VoiceCommands.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/VoiceCommands.c.s
.PHONY : src/VoiceCommands.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/Bike.dir/build.make CMakeFiles/Bike.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Bike"
	@echo "... src/AD_HOC.o"
	@echo "... src/AD_HOC.i"
	@echo "... src/AD_HOC.s"
	@echo "... src/Bluetooth_Phone.o"
	@echo "... src/Bluetooth_Phone.i"
	@echo "... src/Bluetooth_Phone.s"
	@echo "... src/Bluetooth_Pi0W.o"
	@echo "... src/Bluetooth_Pi0W.i"
	@echo "... src/Bluetooth_Pi0W.s"
	@echo "... src/Button_ISR.o"
	@echo "... src/Button_ISR.i"
	@echo "... src/Button_ISR.s"
	@echo "... src/OBDII.o"
	@echo "... src/OBDII.i"
	@echo "... src/OBDII.s"
	@echo "... src/SerialDriver.o"
	@echo "... src/SerialDriver.i"
	@echo "... src/SerialDriver.s"
	@echo "... src/VoiceCommands.o"
	@echo "... src/VoiceCommands.i"
	@echo "... src/VoiceCommands.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

