
###########################################################################################
# Dependencies generated by g++ -MM

AD_HOC.o : AD_HOC.c AD_HOC.h Bluetooth_Pi0W.h
Bluetooth_Phone.o : Bluetooth_Phone.c Bluetooth_Phone.h Bluetooth_Pi0W.h
Bluetooth_Pi0W.o : Bluetooth_Pi0W.c Bluetooth_Pi0W.h VoiceCommands.h
Button_ISR.o : Button_ISR.c Button_ISR.h AD_HOC.h Bluetooth_Pi0W.h VoiceCommands.h
main.o : main.c main.h AD_HOC.h Bluetooth_Phone.h Bluetooth_Pi0W.h Button_ISR.h OBDII.h VoiceCommands.h
OBDII.o : OBDII.c OBDII.h Bluetooth_Pi0W.h
VoiceCommands.o : VoiceCommands.c VoiceCommands.h Bluetooth_Phone.h Bluetooth_Pi0W.h AD_HOC.h

###########################################################################################
# Variables to define the compiler and compiler options

CC = g++
COPTS = -O0 -g
Link =

###########################################################################################
# Definitions for all
all : Bike

# An explicit rule to link each of the projects that we will building (All the .o files) #

Bike : AD_HOC.o Bluetooth_Phone.o Bluetooth_Pi0W.o Button_ISR.o main.o OBDII.o VoiceCommands.o
	$(CC) $(LINK) -o Bike AD_HOC.o Bluetooth_Phone.o Bluetooth_Pi0W.o Button_ISR.o main.o OBDII.o VoiceCommands.o

##########################################################################################
# Implicit rules for compilation

%.o : %.c
	# Compile the given files
	$(CC) $(COPTS) -c $<

#########################################################################################
# A clean rule, clean everything

clean :
	rm -f *.o
	rm -f *.s
	rm -f *.i
	rm -f Bike

##########################################################################################
